#define SETBIT(WORD,BIT) WORD|=1<<BIT
#define CLRBIT(WORD,BIT) WORD&=~(1<<BIT)
#define CPLBIT(WORD,BIT) WORD^=1<<BIT
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define READNIBBLE(WORD,BITSTARTPOS) (WORD>>BITSTARTPOS)&15
#define READBYTE(WORD,BITSTARTPOS) (WORD>>BITSTARTPOS)&255
#define WRITEBIT(WORD,BITSTARTPOS,BIT) WORD=(WORD&~(1<<BITSTARTPOS))|(BIT<<BITSTARTPOS)
#define WRITENIBBLE(WORD,BITSTARTPOS,BIT) WORD=(WORD&~(15<<BITSTARTPOS))|(BIT<<BITSTARTPOS)
#define WRITEBYTE(WORD,BITSTARTPOS,BIT) WORD=(WORD&~(255<<BITSTARTPOS))|(BIT<<BITSTARTPOS)
//#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)  DWORD=((DWORD&~(1<<DBIT))| ((SWORD>>SBIT)&1)<<DBIT)
//#define READWRITEBIT(WORD,WBIT,RBIT)  WORD=((WORD&~(1<<WBIT))| ((WORD>>RBIT)&1)<<WBIT)
